# Generated by Django 3.2.5 on 2021-10-24 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70)),
                ('classId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.classnumber')),
            ],
        ),
        migrations.CreateModel(
            name='absentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default='1', max_length=6)),
                ('month', models.CharField(choices=[('mehr', 'mehr'), ('aban', 'aban'), ('azar', 'azar'), ('daye', 'daye'), ('bahman', 'bahman'), ('esfand', 'esfand'), ('farvardin', 'farvardin'), ('ordibehesht', 'ordibehesht'), ('khordad', 'khordad'), ('tir', 'tir'), ('mordad', 'mordad'), ('shahrivar', 'shahrivar')], default='مهر', max_length=15)),
                ('year', models.CharField(choices=[(1400, 1400), (1401, 1401), (1402, 1402)], default='1400', max_length=6)),
                ('description', models.TextField()),
                ('delay', models.BooleanField(default=True)),
                ('studentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
