# Generated by Django 3.2.5 on 2021-10-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211025_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentstudent',
            name='delay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='absentstudent',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='absentstudent',
            name='month',
            field=models.CharField(choices=[('mehr', 'mehr'), ('aban', 'aban'), ('azar', 'azar'), ('daye', 'daye'), ('bahman', 'bahman'), ('esfand', 'esfand'), ('farvardin', 'farvardin'), ('ordibehesht', 'ordibehesht'), ('khordad', 'khordad'), ('tir', 'tir'), ('mordad', 'mordad'), ('shahrivar', 'shahrivar')], default='mehr', max_length=15),
        ),
    ]
