# Generated by Django 3.2.5 on 2021-10-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_absentstudent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentstudent',
            name='month',
            field=models.CharField(choices=[('mehr', 'مهر'), ('aban', 'aban'), ('azar', 'azar'), ('daye', 'daye'), ('bahman', 'bahman'), ('esfand', 'esfand'), ('farvardin', 'farvardin'), ('ordibehesht', 'ordibehesht'), ('khordad', 'khordad'), ('tir', 'tir'), ('mordad', 'mordad'), ('shahrivar', 'shahrivar')], default='mehr', max_length=15),
        ),
    ]
