# Generated by Django 3.2.5 on 2021-10-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_absentstudent_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentstudent',
            name='month',
            field=models.CharField(choices=[('مهر', 'مهر'), ('آبان', 'آبان'), ('آذر', 'آذر'), ('دی', 'دی'), ('بهمن', 'بهمن'), ('اسفند', 'اسفند'), ('فروردین', 'فروردین'), ('اردیبهشت', 'اردیبهشت'), ('خرداد', 'خرداد'), ('تیر', 'تیر'), ('مرداد', 'مرداد'), ('شهریور', 'شهریور')], default='mehr', max_length=15),
        ),
    ]
