# Generated by Django 3.2.5 on 2021-10-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_absentstudent_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentstudent',
            name='delay',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], default='ندارد', max_length=10),
        ),
    ]
