# Generated by Django 3.2.5 on 2021-10-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_absentstudent_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentstudent',
            name='delay',
            field=models.CharField(choices=[('دارد', 'دارد'), ('غیبت', 'غیبت')], default='ندارد', max_length=10),
        ),
    ]
